apiVersion: v1
kind: Service
metadata:
  name: ndp-svc
spec:
  type: NodePort
  selector:
   app: aig
  ports:
    - port: 8082
      targetPort: 80
      nodePort: 3000
---
apiVersion: v1
kind: Pod
metadata:
  name: testpod2
  labels:
   app: aig
spec:
  containers:
  - image: nginx
    name: testpod2
    ports:
    - containerPort: 80 